### ISSUE TITLE
mvn: Error with com.github.dingxin:proguard-maven-plugin:1.0.4-beta2

### ISSUE THREAD

**Issue by muramura** [ArduPilot/OMC#2]
I get the following error.
There was no 1.0.4beta2 in GITHUB for this plugin.

[ERROR] Plugin com.github.dingxin:proguard-maven-plugin:1.0.4-beta2 or one of its dependencies could not be resolved: Could not find artifact com.github.dingxin:proguard-maven-plugin:jar:1.0.4-beta2 in local-plugin-repository (file:///home/muramura/work/OMC/IntelMissionControl/../maven-local-repository) -> [Help 1]

I changed mine to 1.0.3.
I got the following error.
I am running under UBUNTU 18.04.
Do I need to do it in a windows environment?

[ERROR] Failed to execute goal on project IntelMissionControl: Could not resolve dependencies for project com.intel.missioncontrol:IntelMissionControl:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.openjfx:javafx-graphics-es2:jar:win:12: Failed to read artifact descriptor for org.openjfx:javafx-graphics-es2:jar:win:12: Could not transfer artifact org.openjfx:javafx-graphics-es2:pom:12 from/to central (https://central.maven.org/maven2): central.maven.org: Name or service not known: Unknown host central.maven.org: Name or service not known -> [Help 1]

**Comment by caller** [comment]
fixed
